Análise Titanic

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('titanic.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'titanic.csv'

In [ ]:
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df_teste = df

In [ ]:
df_teste = df_teste.drop(
    columns=[
        "Ticket",
        "Cabin",
        "Fare",
        "Parch",
        "Embarked",
        "SibSp",
        "Pclass",
        "PassengerId"
    ]
)

Limpeza de Dados

In [ ]:
df_teste

     Survived                                               Name     Sex   Age
0           0                            Braund, Mr. Owen Harris    male  22.0
1           1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2           1                             Heikkinen, Miss. Laina  female  26.0
3           1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4           0                           Allen, Mr. William Henry    male  35.0
..        ...                                                ...     ...   ...
886         0                              Montvila, Rev. Juozas    male  27.0
887         1                       Graham, Miss. Margaret Edith  female  19.0
888         0           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889         1                              Behr, Mr. Karl Howell    male  26.0
890         0                                Dooley, Mr. Patrick    male  32.0

[891 rows x 4 columns]

In [ ]:
df_teste["Title"] = df_teste["Name"]

In [ ]:
df_teste["Title"] = df_teste["Name"].str.extract('(Mrs|Mr|Miss|Master)')

In [ ]:
df_teste

,Survived,Name,Sex,Age,Title
0,0,"Braund, Mr. Owen Harris",male,22.0,Mr
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,Mrs
2,1,"Heikkinen, Miss. Laina",female,26.0,Miss
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,Mrs
4,0,"Allen, Mr. William Henry",male,35.0,Mr
...,...,...,...,...,...
886,0,"Montvila, Rev. Juozas",male,27.0,NaN
887,1,"Graham, Miss. Margaret Edith",female,19.0,Miss
888,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,Miss
889,1,"Behr, Mr. Karl Howell",male,26.0,Mr
890,0,"Dooley, Mr. Patrick",male,32.0,Mr

In [ ]:
del df_teste["Name"]

In [ ]:
df_teste

     Survived     Sex   Age Title
0           0    male  22.0    Mr
1           1  female  38.0   Mrs
2           1  female  26.0  Miss
3           1  female  35.0   Mrs
4           0    male  35.0    Mr
..        ...     ...   ...   ...
886         0    male  27.0   NaN
887         1  female  19.0  Miss
888         0  female   NaN  Miss
889         1    male  26.0    Mr
890         0    male  32.0    Mr

[891 rows x 4 columns]

In [ ]:
df_teste.Sex.value_counts(dropna = False)

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
df_teste = pd.get_dummies(df_teste, dtype = int)

In [ ]:
df_teste

,Survived,Age,Sex_female,Sex_male,Title_Master,Title_Miss,Title_Mr,Title_Mrs
0,0,22.0,0,1,0,0,1,0
1,1,38.0,1,0,0,0,0,1
2,1,26.0,1,0,0,1,0,0
3,1,35.0,1,0,0,0,0,1
4,0,35.0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...
886,0,27.0,0,1,0,0,0,0
887,1,19.0,1,0,0,1,0,0
888,0,NaN,1,0,0,1,0,0
889,1,26.0,0,1,0,0,1,0
890,0,32.0,0,1,0,0,1,0

Transformação de dados categóricos em colunas

In [ ]:
df_teste = df_teste.drop(
    columns = [
        "Sex_male",
        "Title_Master"

    ]
)

In [ ]:
df_teste

     Survived   Age  Sex_female  Title_Miss  Title_Mr  Title_Mrs
0           0  22.0           0           0         1          0
1           1  38.0           1           0         0          1
2           1  26.0           1           1         0          0
3           1  35.0           1           0         0          1
4           0  35.0           0           0         1          0
..        ...   ...         ...         ...       ...        ...
886         0  27.0           0           0         0          0
887         1  19.0           1           1         0          0
888         0   NaN           1           1         0          0
889         1  26.0           0           0         1          0
890         0  32.0           0           0         1          0

[891 rows x 6 columns]

Retiramos a coluna Sex_male pois ela já é descoberta com a coluna Sex_female... Retiramos aa coluna TitleMaster pois a maioria é 0 pois já são descobertos em Title_Miss

In [ ]:
df_teste = pd.get_dummies(df_teste, drop_first = True)

In [ ]:
df_teste

     Survived   Age  Sex_female  Title_Miss  Title_Mr  Title_Mrs
0           0  22.0           0           0         1          0
1           1  38.0           1           0         0          1
2           1  26.0           1           1         0          0
3           1  35.0           1           0         0          1
4           0  35.0           0           0         1          0
..        ...   ...         ...         ...       ...        ...
886         0  27.0           0           0         0          0
887         1  19.0           1           1         0          0
888         0   NaN           1           1         0          0
889         1  26.0           0           0         1          0
890         0  32.0           0           0         1          0

[891 rows x 6 columns]

Imputação de dados:

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
coluna = df_teste[["Age"]]

In [ ]:
df_teste['Age'].median()

np.float64(28.0)

In [ ]:
imputacao = SimpleImputer(strategy = "median")

In [ ]:
df_teste["Age"] = imputacao.fit_transform(coluna)

Preenchimento de NaN pela mediana (28.0) de valores contidos na tabela.

In [ ]:
df_teste

     Survived   Age  Sex_female  Title_Miss  Title_Mr  Title_Mrs
0           0  22.0           0           0         1          0
1           1  38.0           1           0         0          1
2           1  26.0           1           1         0          0
3           1  35.0           1           0         0          1
4           0  35.0           0           0         1          0
..        ...   ...         ...         ...       ...        ...
886         0  27.0           0           0         0          0
887         1  19.0           1           1         0          0
888         0  28.0           1           1         0          0
889         1  26.0           0           0         1          0
890         0  32.0           0           0         1          0

[891 rows x 6 columns]

In [ ]:
df_teste["Title"]= df_teste["Sex_female"]

Encoder com Sobreviventes

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder= LabelEncoder()
codificado= encoder.fit_transform(df_teste['Survived'])
codificado

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df_teste['Survived'].unique()

array([0, 1])

In [ ]:
encoder = OrdinalEncoder()
codificado = encoder.fit_transform(df_teste[['Survived']])  
df_codificado = pd.DataFrame(codificado, columns=['Survived'], index=df.index)
df_codificado.value_counts()

Survived
0.0         549
1.0         342
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
encoder = OneHotEncoder()
codificado = encoder.fit_transform(df_teste[['Survived']]).toarray()
#codificado

In [ ]:
df_codificado = pd.DataFrame(
    codificado,
    columns=encoder.get_feature_names_out(['Survived']),
    index=df.index
)
df_codificado

     Survived_0  Survived_1
0           1.0         0.0
1           0.0         1.0
2           0.0         1.0
3           0.0         1.0
4           1.0         0.0
..          ...         ...
886         1.0         0.0
887         0.0         1.0
888         1.0         0.0
889         0.0         1.0
890         1.0         0.0

[891 rows x 2 columns]

Treinamento e Teste:

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()
df_teste['Survided'] = encoder.fit_transform(df_teste['Survived'])

In [ ]:
y = df_teste.Survived
X = df_teste.drop(columns="Survived").select_dtypes(include='number')

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
len(y_train)

712

In [ ]:
modelos = {
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=3),
}

In [ ]:
resultados = {}

for nome, modelo in modelos.items():
    modelo.fit(X_train, y_train)
    Y_pred = modelo.predict(X_test)
    acc = accuracy_score(y_test, Y_pred)
    resultados[nome] = acc

    print(f"\n===== {nome} =====")
    print(f"Acurácia: {acc:.4f}")
    print("Matriz de confusão:")
    print(confusion_matrix(y_test, Y_pred))
    print("Relatório de classificação:")
    print(classification_report(y_test, Y_pred, target_names=encoder.classes_))

# ---------- 6. Comparativo final ----------
print("\n===== Comparativo de Acurácia =====")
for nome, acc in sorted(resultados.items(), key=lambda x: x[1], reverse=True):
    print(f"{nome}: {acc:.4f}")

===== Logistic Regression =====
Acurácia: 1.0000
Matriz de confusão:
[[105   0]
 [  0  74]]
Relatório de classificação:

TypeError: object of type 'numpy.int64' has no len()